language: java
sudo: false # faster builds

jdk:
- oraclejdk11

install: true
cache:
  directories:
  - $HOME/.m2

script:
- ./mvnw verify package

after_success:
- bash <(curl -s https://codecov.io/bash)
